networks:
  proxy:
    name: ${PROXY_NETWORK-proxy}

services:
  nginx:
    build: ./
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${VOLUME_PATH}/conf.d:/etc/nginx/conf.d
      # - ${VOLUME_PATH}/etc/nginx/sites-available:/etc/nginx/sites-available
      # - ${VOLUME_PATH}/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ${VOLUME_PATH}/etc/letsencrypt:/etc/letsencrypt
      - ${VOLUME_PATH}/tmp:/tmp
