networks:
  proxy:
    name: ${PROXY_NETWORK-proxy}

services:
  nginx:
    build:
      context: ./
      args:
        NGINX_TAG: ${NGINX_TAG-stable}
    logging:
      driver: "json-file"
      options:
        max-size: ${LOG_MAX_SIZE-100M}
        max-file: ${LOG_MAX_FILE-3}
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${VOLUME_PATH}/conf.d:/etc/nginx/conf.d
      - ${VOLUME_PATH}/letsencrypt-acme-challenge:/data/letsencrypt-acme-challenge
      - ${VOLUME_PATH}/etc/letsencrypt:/etc/letsencrypt
      - ${VOLUME_PATH}/tmp:/tmp
