networks:
  proxy:
    name: ${PROXY_NETWORK-proxy}

services:
  nginx:
    build:
      context: ./
      args:
        NGINX_TAG: ${NGINX_TAG-stable}
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${VOLUME_PATH}/conf.d:/etc/nginx/conf.d
      - ${VOLUME_PATH}/etc/letsencrypt:/etc/letsencrypt
      - ${VOLUME_PATH}/tmp:/tmp
